function [ nextPosition, stateId, absorb] = ...
combinePush(force1, force2, angle1, angle2, boxPosition, numForce, numAngle, dest)
[xforce, yforce] = ...
    combineForce(force1, force2, angle1, angle2, numForce, numAngle);

[ nextPosition, stateId, absorb] = ...
singleStep( boxPosition, xforce, yforce, dest);
end